name: Cypress E2E Tests v2

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice 
        description: "Select the environment for the test run"
        required: true
        options:
        - dev
        - test
        - prod
        default: "prod"
      tag: 
        description: "Enter test tags - optional"
        required: false
      browser:
        description: "Select the browser to run the tests in"
        type: choice
        required: true
        options:
          - chrome
          - electron
          - firefox
        default: "electron"
        
env:
  ENVIRONMENT: ${{ github.event.inputs.environment }}

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    container: cypress/browsers:node14.16.0-chrome89-ff86
    
    steps:
      - name: Start ${{ github.event.inputs.tag }} Test Run on ${{ env.ENVIRONMENT }}
        run: echo 'Starting Test Run on ${{ env.ENVIRONMENT }}'
        
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
          
      # and run all Cypress tests
      # Prod
      - name: Cypress run on production
        uses: cypress-io/github-action@v2
        timeout-minutes: 5
        if: env.ENVIRONMENT == 'prod'
        with:
          browser: ${{ github.event.inputs.browser }}
          config: baseUrl=https://www.google.com
          record: true
          command-prefix: "--"
          parallel: true
          tag: ${{ env.ENVIRONMENT }}
        env: 
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
      # Test
      - name: Cypress run on test environment
        uses: cypress-io/github-action@v2
        if: env.ENVIRONMENT == 'test'
        timeout-minutes: 5
        with:
          browser: ${{ github.event.inputs.browser }}
          config: baseUrl=https://www.google.com
          record: true
          tag: ${{ env.ENVIRONMENT }}
        env: 
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
      # Dev
      - name: Cypress run on dev environment
        uses: cypress-io/github-action@v2
        if: env.ENVIRONMENT == 'dev'
        timeout-minutes: 5
        with:
          browser: ${{ github.event.inputs.browser }}
          config: baseUrl=https://www.google.com
          record: true
          tag: ${{ env.ENVIRONMENT }}
        env: 
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
      - name: Upload screenshots
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
